version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
